### ISSUE TITLE
Is not loading!

### ISSUE THREAD

**Issue by ghost** [efekoca/web-tools#1]
Hey! 
Thanks for this awesome project. But here i am facing some problems. I have finished all the major things you have mentioned me, like database configuration. But then i am moving this to my root folder (public_html) from web-tools-main, tools are not opening. I mean if i click any tools they are reloading the page. I have checked all types of stuffs! but still not working, tell me how can i fix this.

my site: https://roydigitalnexus.com/
Thanks

**Comment by efekoca** [comment]
Hey, thanks for your interest. I checked your site and didn't see any problem. Everything seems OK right now.

**Comment by ghost** [comment]
Hey!
Boss, it is working now! There was an issue made by me. Sorry for any kind
of inconvenience. Have a nice day!
